deps: Enable rustls
To prevent this breakage on Linux:

    warning: openssl-sys@0.9.111: In file included from /usr/include/openssl/opensslv.h:109,
    warning: openssl-sys@0.9.111:                  from build/expando.c:1:
    warning: openssl-sys@0.9.111: /usr/include/openssl/macros.h:14:10: fatal error: openssl/opensslconf.h: No such file or directory
    warning: openssl-sys@0.9.111:    14 | #include <openssl/opensslconf.h>
    warning: openssl-sys@0.9.111:       |          ^~~~~~~~~~~~~~~~~~~~~~~
    warning: openssl-sys@0.9.111: compilation terminated.
    error: failed to run custom build command for `openssl-sys v0.9.111`
    Caused by:
      process didn't exit successfully: `/home/runner/work/cc2sheets/cc2sheets/target/debug/build/openssl-sys-22c98fcdf2fe513e/build-script-main` (exit status: 101)